This commit was manufactured by cvs2svn to create tag 'release-2-0-11'.
git-svn-id: svn+ssh://svn.abisource.com/svnroot/abiword/tags/release-2-0-11@14646 bcba8976-2d24-0410-9c9c-aab3bd5fdfd6

diff --git a/src/pkg/win/setup/Makefile b/src/pkg/win/setup/Makefile
--- a/src/pkg/win/setup/Makefile
+++ b/src/pkg/win/setup/Makefile
@@ -23,8 +23,7 @@ ABI_ROOT:=$(shell pwd)/../../../..
 include $(ABI_ROOT)/src/config/abi_defs.mk
 
 ifeq ($(ABI_OPT_NSIS_20),1)
-#PROGRAM=		$(BINDIR)/setup_abiword.${ABI_BUILD_VERSION_MAJOR}-$(ABI_BUILD_VERSION_MINOR)-${ABI_BUILD_VERSION_MICRO}.exe
-PROGRAM=		$(BINDIR)/setup_abiword.exe
+PROGRAM=		$(BINDIR)/setup_abiword.${ABI_BUILD_VERSION_MAJOR}-$(ABI_BUILD_VERSION_MINOR)-${ABI_BUILD_VERSION_MICRO}.exe
 else
 PROGRAM=		$(BINDIR)/setup_abiword.exe
 endif
@@ -37,34 +36,50 @@ include $(ABI_ROOT)/src/config/abi_rules.mk
 ## everything below here must *FOLLOW* abi_rules
 ##################################################################
 
-ifeq ($(ABI_OPT_NSIS_20),1)
-NSIS_SRC = ./AbiWord2.nsi
-NSIS_OPT =  /DVERSION=$(ABI_BUILD_VERSION) /DVERSION_MAJOR=$(ABI_BUILD_VERSION_MAJOR)
-NSIS_OPT += /DVERSION_MINOR=$(ABI_BUILD_VERSION_MINOR) /DVERSION_MICRO=$(ABI_BUILD_VERSION_MICRO)
-ifdef NSIS_CRTL_URL
-#e.g. NSIS_CRTL_URL=http://abiword.pchasm.org/microsoft/ NSIS_CRTL_FILENAME=msvcr70.dll
-NSIS_OPT += /DOPT_CRTL_URL=$(NSIS_CRTL_URL) /DOPT_CRTL_FILENAME=$(NSIS_CRTL_FILENAME)
-endif
+# MinGW needs to escape NSIS's parameter switch, but not for Cygwin make (MSVC build)
+# but only sometimes, sometimes it doesn't matter, sometimes using it fails, I'm so confused...
+ifeq ($(OS_NAME),MINGW32)
+NSIS_DEF = "//D"
 else
+NSIS_DEF = "/D"
+endif
+
+
+ifeq ($(ABI_OPT_NSIS_20),1)
+
+NSIS_SRC =  ./NSISv2/*.ns*
+NSIS_OPT =  $(NSIS_DEF)VERSION=$(ABI_BUILD_VERSION) $(NSIS_DEF)VERSION_MAJOR=$(ABI_BUILD_VERSION_MAJOR)
+NSIS_OPT += $(NSIS_DEF)VERSION_MINOR=$(ABI_BUILD_VERSION_MINOR) $(NSIS_DEF)VERSION_MICRO=$(ABI_BUILD_VERSION_MICRO)
+#e.g. NSIS_CRTL_URL=http://abiword.pchasm.org/microsoft/ NSIS_CRTL_FILENAME=msvcr70.dll
+#or   NSIS_CRTL_LOCAL=\MS\REDIST\ NSIS_CRTL_FILENAME=msvcrt.dll NSIS_CRTL_WIN95ONLY
+
+ifdef NSIS_CRTL_LOCAL
+NSIS_OPT += $(NSIS_DEF)OPT_CRTL_LOCAL=$(NSIS_CRTL_LOCAL)
+endif
+ifdef NSIS_CRTL_URL
+NSIS_OPT += /DOPT_CRTL_URL=$(NSIS_CRTL_URL)
+endif
+ifdef NSIS_CRTL_FILENAME
+NSIS_OPT += $(NSIS_DEF)OPT_CRTL_FILENAME=$(NSIS_CRTL_FILENAME)
+else
+NSIS_OPT += $(NSIS_DEF)OPT_CRTL_FILENAME=msvcrt.dll
+endif
+ifeq ($(NSIS_CRTL_WIN95ONLY),1)
+NSIS_OPT += $(NSIS_DEF)OPT_CRTL_WIN95ONLY
+endif
+
+else #($(ABI_OPT_NSIS_20),1)
 NSIS_SRC = ./AbiWord.nsi
 NSIS_OPT = 
 endif
 
 ifeq ($(OS_NAME),MINGW32)
-NSIS_OPT += //DMINGW32=1
-endif
-
-ifneq ($(wildcard $(ABI_ROOT)/../abiword-plugins/wp/impexp/graphics/bmp),)
-ifeq ($(OS_NAME),MINGW32)
-NSIS_OPT += //DHAVEBMP=1
-else
-NSIS_OPT += /DHAVEBMP=1
-endif
+NSIS_OPT += $(NSIS_DEF)MINGW32=1
 endif
 
 $(PROGRAM): $(BINDIR)/makensis$(EXE_SUFFIX)
-	@rm -f $(BINDIR)/AbiWord.nsi; \
-	$(ABICOPY) $(NSIS_SRC) $(BINDIR)/AbiWord.nsi; \
+	@rm -f $(BINDIR)/*.ns*; \
+	$(ABICOPY) $(NSIS_SRC) $(BINDIR)/; \
 	cd $(BINDIR); \
 	$(BINDIR)/makensis$(EXE_SUFFIX) $(NSIS_OPT) ./AbiWord.nsi
 
@@ -79,15 +94,16 @@ _NSIS_:
 		exit 1;								\
 	fi
 
-_BMP_PLUGIN_:
-	@if [ -d $(ABI_ROOT)/../abiword-plugins/wp/impexp/graphics/bmp ]; then	\
-		echo Found BMP graphic file filter plugin;	\
-		echo Building for use with Windows cut and paste support;	\
-		$(MAKE) -f Makefile -C $(ABI_ROOT)/../abiword-plugins/wp/impexp/graphics/bmp;	\
+_W32NATIVE_PLUGIN_:
+	@if [ -d $(ABI_ROOT)/../abiword-plugins/wp/impexp/graphics/win32native ]; then	\
+		echo Found win32native graphic file filter plugin;	\
+		echo Building for use with Windows cut and paste support and importers;	\
+		$(MAKE) -f Makefile -C $(ABI_ROOT)/../abiword-plugins/wp/impexp/graphics/win32native;	\
 	else	\
-		echo BMP graphic file filter plugin NOT found;	\
-		echo Please ignore the warning generated by NSIS about this file missing;	\
-		echo However, cut and paste support may not work for images without this plugin!;	\
+		echo WARNING: win32native graphic file filter plugin NOT found;	\
+		echo Please download the peer abiword-plugins directory \
+		echo Document import and cut-n-paste will not support standard image formats!;	\
+		exit 1;	\
 	fi
 
 ifeq ($(ABI_OPT_DEBUG),1)
@@ -99,7 +115,7 @@ distribution::
 
 else
 
-distribution:: _NSIS_ _BMP_PLUGIN_ $(TARGETS)
+distribution:: _NSIS_ _W32NATIVE_PLUGIN_ $(TARGETS)
 	@echo Copying $(PROGRAM) to $(DIST)
 	@$(subst xxxx,$(DIST),$(VERIFY_DIRECTORY))
 	@$(ABICOPY) $(PROGRAM) $(DIST)
